### ISSUE TITLE
demo gif

### ISSUE THREAD

**Issue by sublimemm** [extrawurst/godot-vs-rapier#2]
Just wondering why the demo gif was so different for the godot vs rapier test. You can see in the godot test the bodies continuously bounce off each other, probably hundreds of thousands of collisions. In the rapier test the bodies just sit statically, I would not be surprised if the godot demo would also maintain FPS if the bodies weren't colliding. 

I don't doubt that rapier is faster or better, but the demo gif gives me complete mistrust of the 'apples to apples' comparison. 

I noticed because one of our games has a massive FPS drop when the bodies collide EXACTLY like in the godot demo, but have no problem when the bodies aren't colliding like crazy (even though the number of bodies is unchanged).

**Comment by extrawurst** [comment]
it is for sure not an apples to apples comparison, Godot has a 5 year old issue for this: https://github.com/godotengine/godot/issues/2092 - but right now its all I have to compare against :)

**Comment by sublimemm** [comment]
Haha, I see. I didn't realize that was a godot issue! Yeah if you can't replicate the behavior because it doesn't exist, I'd call that solved lol.
